// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event_id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"invaded", "movement"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "invader_event_id", Type: field.TypeInt, Nullable: true},
		{Name: "movement_event_id", Type: field.TypeInt, Nullable: true},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_invaders_event_id",
				Columns:    []*schema.Column{EventsColumns[4]},
				RefColumns: []*schema.Column{InvadersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "events_movements_event_id",
				Columns:    []*schema.Column{EventsColumns[5]},
				RefColumns: []*schema.Column{MovementsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// InvadersColumns holds the columns for the "invaders" table.
	InvadersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "picture", Type: field.TypeBytes},
		{Name: "confidence", Type: field.TypeFloat64},
	}
	// InvadersTable holds the schema information for the "invaders" table.
	InvadersTable = &schema.Table{
		Name:       "invaders",
		Columns:    InvadersColumns,
		PrimaryKey: []*schema.Column{InvadersColumns[0]},
	}
	// MovementsColumns holds the columns for the "movements" table.
	MovementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "picture", Type: field.TypeBytes},
	}
	// MovementsTable holds the schema information for the "movements" table.
	MovementsTable = &schema.Table{
		Name:       "movements",
		Columns:    MovementsColumns,
		PrimaryKey: []*schema.Column{MovementsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		InvadersTable,
		MovementsTable,
	}
)

func init() {
	EventsTable.ForeignKeys[0].RefTable = InvadersTable
	EventsTable.ForeignKeys[1].RefTable = MovementsTable
}
