// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nkust-monitor-iot-project-2024/central/ent/invader"
)

// Invader is the model entity for the Invader schema.
type Invader struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Picture holds the value of the "picture" field.
	Picture []byte `json:"picture,omitempty"`
	// Confidence holds the value of the "confidence" field.
	Confidence float64 `json:"confidence,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvaderQuery when eager-loading is set.
	Edges        InvaderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvaderEdges holds the relations/edges for other nodes in the graph.
type InvaderEdges struct {
	// EventID holds the value of the event_id edge.
	EventID []*Event `json:"event_id,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventIDOrErr returns the EventID value or an error if the edge
// was not loaded in eager-loading.
func (e InvaderEdges) EventIDOrErr() ([]*Event, error) {
	if e.loadedTypes[0] {
		return e.EventID, nil
	}
	return nil, &NotLoadedError{edge: "event_id"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Invader) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invader.FieldPicture:
			values[i] = new([]byte)
		case invader.FieldConfidence:
			values[i] = new(sql.NullFloat64)
		case invader.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Invader fields.
func (i *Invader) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case invader.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		case invader.FieldPicture:
			if value, ok := values[j].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field picture", values[j])
			} else if value != nil {
				i.Picture = *value
			}
		case invader.FieldConfidence:
			if value, ok := values[j].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[j])
			} else if value.Valid {
				i.Confidence = value.Float64
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Invader.
// This includes values selected through modifiers, order, etc.
func (i *Invader) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// QueryEventID queries the "event_id" edge of the Invader entity.
func (i *Invader) QueryEventID() *EventQuery {
	return NewInvaderClient(i.config).QueryEventID(i)
}

// Update returns a builder for updating this Invader.
// Note that you need to call Invader.Unwrap() before calling this method if this Invader
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Invader) Update() *InvaderUpdateOne {
	return NewInvaderClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Invader entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Invader) Unwrap() *Invader {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Invader is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Invader) String() string {
	var builder strings.Builder
	builder.WriteString("Invader(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("picture=")
	builder.WriteString(fmt.Sprintf("%v", i.Picture))
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", i.Confidence))
	builder.WriteByte(')')
	return builder.String()
}

// Invaders is a parsable slice of Invader.
type Invaders []*Invader
