// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nkust-monitor-iot-project-2024/central/ent/event"
	"github.com/nkust-monitor-iot-project-2024/central/ent/movement"
	"github.com/nkust-monitor-iot-project-2024/central/ent/predicate"
)

// MovementUpdate is the builder for updating Movement entities.
type MovementUpdate struct {
	config
	hooks    []Hook
	mutation *MovementMutation
}

// Where appends a list predicates to the MovementUpdate builder.
func (mu *MovementUpdate) Where(ps ...predicate.Movement) *MovementUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetPicture sets the "picture" field.
func (mu *MovementUpdate) SetPicture(b []byte) *MovementUpdate {
	mu.mutation.SetPicture(b)
	return mu
}

// AddEventIDIDs adds the "event_id" edge to the Event entity by IDs.
func (mu *MovementUpdate) AddEventIDIDs(ids ...uuid.UUID) *MovementUpdate {
	mu.mutation.AddEventIDIDs(ids...)
	return mu
}

// AddEventID adds the "event_id" edges to the Event entity.
func (mu *MovementUpdate) AddEventID(e ...*Event) *MovementUpdate {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return mu.AddEventIDIDs(ids...)
}

// Mutation returns the MovementMutation object of the builder.
func (mu *MovementUpdate) Mutation() *MovementMutation {
	return mu.mutation
}

// ClearEventID clears all "event_id" edges to the Event entity.
func (mu *MovementUpdate) ClearEventID() *MovementUpdate {
	mu.mutation.ClearEventID()
	return mu
}

// RemoveEventIDIDs removes the "event_id" edge to Event entities by IDs.
func (mu *MovementUpdate) RemoveEventIDIDs(ids ...uuid.UUID) *MovementUpdate {
	mu.mutation.RemoveEventIDIDs(ids...)
	return mu
}

// RemoveEventID removes "event_id" edges to Event entities.
func (mu *MovementUpdate) RemoveEventID(e ...*Event) *MovementUpdate {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return mu.RemoveEventIDIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MovementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MovementUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MovementUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MovementUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MovementUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(movement.Table, movement.Columns, sqlgraph.NewFieldSpec(movement.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Picture(); ok {
		_spec.SetField(movement.FieldPicture, field.TypeBytes, value)
	}
	if mu.mutation.EventIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movement.EventIDTable,
			Columns: movement.EventIDPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedEventIDIDs(); len(nodes) > 0 && !mu.mutation.EventIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movement.EventIDTable,
			Columns: movement.EventIDPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.EventIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movement.EventIDTable,
			Columns: movement.EventIDPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MovementUpdateOne is the builder for updating a single Movement entity.
type MovementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MovementMutation
}

// SetPicture sets the "picture" field.
func (muo *MovementUpdateOne) SetPicture(b []byte) *MovementUpdateOne {
	muo.mutation.SetPicture(b)
	return muo
}

// AddEventIDIDs adds the "event_id" edge to the Event entity by IDs.
func (muo *MovementUpdateOne) AddEventIDIDs(ids ...uuid.UUID) *MovementUpdateOne {
	muo.mutation.AddEventIDIDs(ids...)
	return muo
}

// AddEventID adds the "event_id" edges to the Event entity.
func (muo *MovementUpdateOne) AddEventID(e ...*Event) *MovementUpdateOne {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return muo.AddEventIDIDs(ids...)
}

// Mutation returns the MovementMutation object of the builder.
func (muo *MovementUpdateOne) Mutation() *MovementMutation {
	return muo.mutation
}

// ClearEventID clears all "event_id" edges to the Event entity.
func (muo *MovementUpdateOne) ClearEventID() *MovementUpdateOne {
	muo.mutation.ClearEventID()
	return muo
}

// RemoveEventIDIDs removes the "event_id" edge to Event entities by IDs.
func (muo *MovementUpdateOne) RemoveEventIDIDs(ids ...uuid.UUID) *MovementUpdateOne {
	muo.mutation.RemoveEventIDIDs(ids...)
	return muo
}

// RemoveEventID removes "event_id" edges to Event entities.
func (muo *MovementUpdateOne) RemoveEventID(e ...*Event) *MovementUpdateOne {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return muo.RemoveEventIDIDs(ids...)
}

// Where appends a list predicates to the MovementUpdate builder.
func (muo *MovementUpdateOne) Where(ps ...predicate.Movement) *MovementUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MovementUpdateOne) Select(field string, fields ...string) *MovementUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Movement entity.
func (muo *MovementUpdateOne) Save(ctx context.Context) (*Movement, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MovementUpdateOne) SaveX(ctx context.Context) *Movement {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MovementUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MovementUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MovementUpdateOne) sqlSave(ctx context.Context) (_node *Movement, err error) {
	_spec := sqlgraph.NewUpdateSpec(movement.Table, movement.Columns, sqlgraph.NewFieldSpec(movement.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Movement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, movement.FieldID)
		for _, f := range fields {
			if !movement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != movement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Picture(); ok {
		_spec.SetField(movement.FieldPicture, field.TypeBytes, value)
	}
	if muo.mutation.EventIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movement.EventIDTable,
			Columns: movement.EventIDPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedEventIDIDs(); len(nodes) > 0 && !muo.mutation.EventIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movement.EventIDTable,
			Columns: movement.EventIDPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.EventIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   movement.EventIDTable,
			Columns: movement.EventIDPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Movement{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
