// Code generated by ent, DO NOT EDIT.

package movement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the movement type in the database.
	Label = "movement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPicture holds the string denoting the picture field in the database.
	FieldPicture = "picture"
	// EdgeEventID holds the string denoting the event_id edge name in mutations.
	EdgeEventID = "event_id"
	// Table holds the table name of the movement in the database.
	Table = "movements"
	// EventIDTable is the table that holds the event_id relation/edge.
	EventIDTable = "events"
	// EventIDInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventIDInverseTable = "events"
	// EventIDColumn is the table column denoting the event_id relation/edge.
	EventIDColumn = "movement_event_id"
)

// Columns holds all SQL columns for movement fields.
var Columns = []string{
	FieldID,
	FieldPicture,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Movement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventIDCount orders the results by event_id count.
func ByEventIDCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventIDStep(), opts...)
	}
}

// ByEventID orders the results by event_id terms.
func ByEventID(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventIDStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEventIDStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventIDInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventIDTable, EventIDColumn),
	)
}
