// Code generated by ent, DO NOT EDIT.

package movement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the movement type in the database.
	Label = "movement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPicture holds the string denoting the picture field in the database.
	FieldPicture = "picture"
	// EdgeEvent holds the string denoting the event edge name in mutations.
	EdgeEvent = "event"
	// Table holds the table name of the movement in the database.
	Table = "movements"
	// EventTable is the table that holds the event relation/edge. The primary key declared below.
	EventTable = "event_movements"
	// EventInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventInverseTable = "events"
)

// Columns holds all SQL columns for movement fields.
var Columns = []string{
	FieldID,
	FieldPicture,
}

var (
	// EventPrimaryKey and EventColumn2 are the table columns denoting the
	// primary key for the event relation (M2M).
	EventPrimaryKey = []string{"event_id", "movement_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Movement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventCount orders the results by event count.
func ByEventCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventStep(), opts...)
	}
}

// ByEvent orders the results by event terms.
func ByEvent(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, EventTable, EventPrimaryKey...),
	)
}
